name: work_kursovaya
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # dont work firebsse(fail work)
  # firebase_core: ^2.24.2
  # firebase_auth: ^4.15.3
  # firebase_messaging: ^14.7.9
  # cloud_firestore: ^4.13.6
  # firebase_storage: ^11.5.6
  # flutter_local_notifications: ^16.2.0
  # google_sign_in: ^6.1.6
  provider: ^6.0.0
  shared_preferences: ^2.2.2  
  intl: ^0.18.1
  image_picker: ^0.8.4+4
  flutter_local_notifications: ^9.1.5
  # maps google
  google_maps_flutter: ^2.5.0
  location: ^5.0.3
  geocoding: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
