name: work_kursovaya
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  provider: ^6.0.5
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1
  shared_preferences: ^2.2.2
  intl: ^0.20.2
  image_picker: ^1.1.2
  google_maps_flutter: ^2.5.0
  location: ^8.0.0
  geocoding: ^3.0.0
  cloud_firestore: ^5.6.2
  google_sign_in: ^6.2.2
  firebase_auth_web: ^5.8.13
dependency_overrides:
  firebase_core_platform_interface: 4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
